[package]
name = "ssync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.1"
clap = { version = "3.2.22", features = ["derive"] }
anyhow = "1.0"
pathdiff = "0.2.1"
regex = "1.6.0"
